spring:
  datasource:
    url: jdbc:mysql://121.36.65.13 :3306/csapp?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 5201314Cxy
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  check-config-location: true # ????MyBatis????????
  mapper-locations: classpath:/mapper/*.xml

server:
  port:
    8090
    #ssl:
    # key-store: classpath:hnulab.tech.jks
  #key-store-password: t2pmgxfe
  # keyStoreType: JKS
